import configparser
import os

configfile = 'C:/Users/rfechtner/PycharmProjects/webflowpy/config.ini'
"""Config file path"""

try:
    config = configparser.ConfigParser()
    config.read(configfile)
except Exception:
    config = {
        'General': {},
        'Webflow': {}
    }

if config.has_option('Webflow', 'token'):
    token = config['Webflow']['token']
elif 'WEBFLOW_ACCESS_TOKEN' in os.environ:
    token = os.environ['WEBFLOW_ACCESS_TOKEN']
else:
    token = ''
"""API Access Token. Generated by Webflow under Dashboard > Project Settings > Integrations > API Access"""

if config.has_option('Webflow', 'abort_on_error'):
    abort_on_error = bool(config['Webflow']['abort_on_error'])
else:
    abort_on_error = True
""" 1 Abort execution after first error
0 Continue after error"""

if config.has_option('Webflow', 'retries'):
    retries = int(config['Webflow']['retries'])
else:
    retries = 3
"""max number of retries after 500 or 429 error """

if config.has_option('Webflow', 'backoff_factor'):
    backoff_factor = int(config['Webflow']['backoff_factor'])
else:
    backoff_factor = 20
"""{backoff factor} * (2 ^ ({number of total retries} - 1)) delay after unsuccessfull 500 or 429 requests"""
